
LAB 11 Solutions and Explanations

Qn 1: Use the weblinks and reproduce the results for Linear regression, Logistic regression, SVM and PCA

B) Logisitic regression : https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html


In [29]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
#print characteristics of dataset 
data = load_iris()
print("names of dataset columns:", list(data.feature_names))
print("target names:", list(data.target_names))

#print dataset dimensions and shape
X, y = load_iris(return_X_y=True)
print("X dim:",X.ndim)
print("X rows/samples:",X.shape[0])
print("X cols/features:",X.shape[1])
#print(y)#three classes of iris (0,1,2)

print("y dim:",y.ndim)
print("y rows/samples value:",y.shape[0])

names of dataset columns: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
target names: ['setosa', 'versicolor', 'virginica']
X dim: 2
X rows/samples: 150
X cols/features: 4
y dim: 1
y rows/samples value: 150




class sklearn.linear_model.LogisticRegression(penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)

In [30]:
print("using default initialisation parameters")
clf = LogisticRegression(random_state=0, max_iter=1000).fit(X, y)
print("log reg prediction:", clf.predict(X[:2, :]))
print("log reg prediction score:", clf.score(X, y))
print("coefficient of features in decision function:", clf.coef_)
print("bias:", clf.intercept_)
print("number of iterations accross all classes:", clf.n_iter_)
print("parameters list for model:", clf.get_params())

using default initialisation parameters
log reg prediction: [0 0]
log reg prediction score: 0.9733333333333334
coefficient of features in decision function: [[-0.42316549  0.96688516 -2.51669376 -1.08078412]
 [ 0.53431322 -0.32159716 -0.20666272 -0.94355211]
 [-0.11114773 -0.645288    2.72335648  2.02433623]]
bias: [  9.84902418   2.23817992 -12.0872041 ]
number of iterations accross all classes: [115]
parameters list for model: {'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 1000, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': 0, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


In [31]:
print("using fit_intercept=False")
clf = LogisticRegression(random_state=0, max_iter=1000, fit_intercept=False).fit(X, y)
print("log reg prediction:", clf.predict(X[:2, :]))
print("log reg prediction score:", clf.score(X, y))
print("coefficient of features in decision function:", clf.coef_)
print("bias:", clf.intercept_)
print("number of iterations accross all classes:", clf.n_iter_)
print("parameters list for model:", clf.get_params())

using fit_intercept=False
log reg prediction: [0 0]
log reg prediction score: 0.9666666666666667
coefficient of features in decision function: [[ 0.77433982  1.74702228 -2.34860274 -1.11227851]
 [ 0.6234361  -0.09428645 -0.04476242 -1.02178783]
 [-1.39777592 -1.65273583  2.39336516  2.13406633]]
bias: [0. 0. 0.]
number of iterations accross all classes: [50]
parameters list for model: {'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': False, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 1000, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': 0, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


In [32]:
print("using tol=0.1")
clf = LogisticRegression(random_state=0, max_iter=1000, tol=0.01).fit(X, y)
print("log reg prediction:", clf.predict(X[:2, :]))
print("log reg prediction score:", clf.score(X, y))
print("coefficient of features in decision function:", clf.coef_)
print("bias:", clf.intercept_)
print("number of iterations accross all classes:", clf.n_iter_)
print("parameters list for model:", clf.get_params())

using tol=0.1
log reg prediction: [0 0]
log reg prediction score: 0.9733333333333334
coefficient of features in decision function: [[-0.42331915  0.96662855 -2.51650116 -1.08076895]
 [ 0.53417397 -0.32126057 -0.20653936 -0.94363811]
 [-0.11085481 -0.64536799  2.72304052  2.02440706]]
bias: [  9.8496201   2.237713  -12.0873331]
number of iterations accross all classes: [111]
parameters list for model: {'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 1000, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': 0, 'solver': 'lbfgs', 'tol': 0.01, 'verbose': 0, 'warm_start': False}


In [33]:
print("using multi_class='multinomial' or cross entropy loss funtion")
clf = LogisticRegression(random_state=0, max_iter=1000, multi_class='multinomial').fit(X, y)
print("log reg prediction:", clf.predict(X[:2, :]))
print("log reg prediction score:", clf.score(X, y))
print("coefficient of features in decision function:", clf.coef_)
print("bias:", clf.intercept_)
print("number of iterations accross all classes:", clf.n_iter_)
print("parameters list for model:", clf.get_params())

using multi_class='multinomial' or cross entropy loss funtion
log reg prediction: [0 0]
log reg prediction score: 0.9733333333333334
coefficient of features in decision function: [[-0.42316549  0.96688516 -2.51669376 -1.08078412]
 [ 0.53431322 -0.32159716 -0.20666272 -0.94355211]
 [-0.11114773 -0.645288    2.72335648  2.02433623]]
bias: [  9.84902418   2.23817992 -12.0872041 ]
number of iterations accross all classes: [115]
parameters list for model: {'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 1000, 'multi_class': 'multinomial', 'n_jobs': None, 'penalty': 'l2', 'random_state': 0, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


In [34]:
print("using class_weight=’balanced’")
#The “balanced” mode uses the values of y to automatically adjust weights inversely proportional to class frequencies in the input data as n_samples / (n_classes * np.bincount(y)).
clf = LogisticRegression(random_state=0, max_iter=1000, class_weight='balanced').fit(X, y)
print("log reg prediction:", clf.predict(X[:2, :]))
print("log reg prediction score:", clf.score(X, y))
print("coefficient of features in decision function:", clf.coef_)
print("bias:", clf.intercept_)
print("number of iterations accross all classes:", clf.n_iter_)
print("parameters list for model:", clf.get_params())

using class_weight=’balanced’
log reg prediction: [0 0]
log reg prediction score: 0.9733333333333334
coefficient of features in decision function: [[-0.42316549  0.96688516 -2.51669376 -1.08078412]
 [ 0.53431322 -0.32159716 -0.20666272 -0.94355211]
 [-0.11114773 -0.645288    2.72335648  2.02433623]]
bias: [  9.84902418   2.23817992 -12.0872041 ]
number of iterations accross all classes: [115]
parameters list for model: {'C': 1.0, 'class_weight': 'balanced', 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 1000, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': 0, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


In [35]:
print("using random initial sample weight")
clf = LogisticRegression(random_state=0, max_iter=1000).fit(X, y, sample_weight = np.random.uniform(low=0.0, high=1.0, size=(150,)))
print("log reg prediction:", clf.predict(X[:2, :]))
print("log reg prediction score:", clf.score(X, y))
print("coefficient of features in decision function:", clf.coef_)
print("bias:", clf.intercept_)
print("number of iterations accross all classes:", clf.n_iter_)
print("parameters list for model:", clf.get_params())

using random initial sample weight
log reg prediction: [0 0]
log reg prediction score: 0.9866666666666667
coefficient of features in decision function: [[-0.33775018  0.78866935 -2.06574858 -0.86349043]
 [ 0.53147415 -0.36195354 -0.19742574 -0.5836602 ]
 [-0.19372397 -0.42671581  2.26317432  1.44715063]]
bias: [ 7.85588175  1.42504059 -9.28092234]
number of iterations accross all classes: [82]
parameters list for model: {'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 1000, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': 0, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


In [36]:
print("using stronger regularisation strength")
clf = LogisticRegression(random_state=0, max_iter=1000, C= 0.1).fit(X, y)
print("log reg prediction:", clf.predict(X[:2, :]))
print("log reg prediction score:", clf.score(X, y))
print("coefficient of features in decision function:", clf.coef_)
print("bias:", clf.intercept_)
print("number of iterations accross all classes:", clf.n_iter_)
print("parameters list for model:", clf.get_params())

using stronger regularisation strength
log reg prediction: [0 0]
log reg prediction score: 0.96
coefficient of features in decision function: [[-0.30245855  0.34626876 -1.1811841  -0.48002144]
 [ 0.0709291  -0.33152656  0.07289077 -0.23053665]
 [ 0.23152945 -0.0147422   1.10829333  0.71055808]]
bias: [ 5.32612723  1.59006332 -6.91619054]
number of iterations accross all classes: [89]
parameters list for model: {'C': 0.1, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 1000, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': 0, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}


In [37]:
print("using all above combinations")
clf = LogisticRegression(random_state=0, max_iter=1000, tol=0.01, multi_class='multinomial', class_weight='balanced', C= 0.1).fit(X, y, sample_weight = np.random.uniform(low=0.0, high=1.0, size=(150,)))
print("log reg prediction:", clf.predict(X[:2, :]))
print("log reg prediction score:", clf.score(X, y))
print("coefficient of features in decision function:", clf.coef_)
print("bias:", clf.intercept_)
print("number of iterations accross all classes:", clf.n_iter_)
print("parameters list for model:", clf.get_params())

using all above combinations
log reg prediction: [0 0]
log reg prediction score: 0.92
coefficient of features in decision function: [[-0.25977341  0.2341419  -0.88200269 -0.35111435]
 [ 0.05135223 -0.26560597  0.09105536 -0.11445946]
 [ 0.20842119  0.03146407  0.79094733  0.46557381]]
bias: [ 4.1862718   0.91712984 -5.10340164]
number of iterations accross all classes: [42]
parameters list for model: {'C': 0.1, 'class_weight': 'balanced', 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 1000, 'multi_class': 'multinomial', 'n_jobs': None, 'penalty': 'l2', 'random_state': 0, 'solver': 'lbfgs', 'tol': 0.01, 'verbose': 0, 'warm_start': False}


In [38]:
print("tuning C using all above combinations for stronger regularisation")
clf = LogisticRegression(random_state=0, max_iter=1000, tol=0.01, multi_class='multinomial', class_weight='balanced', C= 0.01).fit(X, y, sample_weight = np.random.uniform(low=0.0, high=1.0, size=(150,)))
print("log reg prediction:", clf.predict(X[:2, :]))
print("log reg prediction score:", clf.score(X, y))
print("coefficient of features in decision function:", clf.coef_)
print("bias:", clf.intercept_)
print("number of iterations accross all classes:", clf.n_iter_)
print("parameters list for model:", clf.get_params())

tuning C using all above combinations for stronger regularisation
log reg prediction: [0 0]
log reg prediction score: 0.7333333333333333
coefficient of features in decision function: [[-0.10083708  0.05557641 -0.30407806 -0.12379092]
 [ 0.00249148 -0.05393023  0.05472994  0.00277643]
 [ 0.0983456  -0.00164618  0.24934813  0.12101449]]
bias: [ 1.58790014  0.00161533 -1.58951547]
number of iterations accross all classes: [32]
parameters list for model: {'C': 0.01, 'class_weight': 'balanced', 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 1000, 'multi_class': 'multinomial', 'n_jobs': None, 'penalty': 'l2', 'random_state': 0, 'solver': 'lbfgs', 'tol': 0.01, 'verbose': 0, 'warm_start': False}
